# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

jobs:
  build:
    docker:
      - image: devin122/omtalk-ci:latest  # hack until we get something better set up
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get intall cmake ninja-build
      - checkout
      - run: git submodule sync
      - run: .circleci/update_submodules.sh
      - run: .circleci/build.sh

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  work:
    # Run the welcome/run job in its own container
    jobs:
      - build
steps:
  - save_cache:
      key: v1-myapp-cache
      paths:
        - ~/d1